modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ftbbackups2"
version = "${version}"
displayName = "FTB Backups 2"
authors = "CreeperHost"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
Backup all the things!
'''
#logoFile = ""

[[dependencies.ftbbackups2]]
modId = "neoforge"
type="required"
versionRange = "[21.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbbackups2]]
modId = "minecraft"
type="required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbbackups2]]
modId = "architectury"
type="required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"
